# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager_prod
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# validate -> verifica que las tablas existan en BD pero no modifican
# migraciones en prod las maneja "flyway" (se agrega despues)
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=false
# no mostramos SQL en prod por tema de seguridad + performance
spring.h2.console.enabled=false

logging.level.com.myapp.taskmanager=INFO
logging.level.org.springframework=WARN